# Generated by Django 5.2.17 on 2026-08-14 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('periodic', 'Periodic'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('duration_days', models.PositiveIntegerField(default=7, help_text='Length of the plan in days')),
                ('duration_label', models.CharField(default='7 Days', max_length=50)),
                ('roi_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Return as a percentage of the invested amount', max_digits=6)),
                ('return_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed return amount per investment', max_digits=16)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=16)),
                ('expected_return', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('maturity_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_investments', to='investments.investmentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
