# Generated by Django 5.2.17 on 2026-08-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_account_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_routing_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='method',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('bank', 'Bank Transfer')], default='crypto', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
